# Generated by Django 6.0.1 on 2026-01-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(),
        ),
    ]
