# Generated by Django 6.0.1 on 2026-01-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enquiry'),
    ]

    atomic = False

    def clear_itinerary(apps, schema_editor):
        Trip = apps.get_model('core', 'Trip')
        Trip.objects.all().update(itinerary='[]')

    operations = [
        migrations.RunPython(clear_itinerary),
    ]
