# Generated by Django 6.0.1 on 2026-01-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trip_exclusions_trip_highlights_trip_inclusions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='exclusions',
            field=models.JSONField(blank=True, help_text='List of excluded items', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='highlights',
            field=models.JSONField(blank=True, help_text='List of trip highlights', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='inclusions',
            field=models.JSONField(blank=True, help_text='List of included items', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='itinerary',
            field=models.JSONField(blank=True, help_text='List of daily itinerary objects', null=True),
        ),
    ]
