# Generated by Django 6.0.1 on 2026-01-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trip_exclusions_trip_highlights_trip_inclusions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
