# Generated by Django 6.0.1 on 2026-02-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stat identifier, e.g. trips_completed', max_length=80, unique=True)),
                ('label', models.CharField(help_text='Display label shown on frontend', max_length=120)),
                ('value', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='📊', help_text='Emoji icon for display', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Stat',
                'verbose_name_plural': 'Site Stats',
            },
        ),
    ]
