# Generated by Django 6.0.1 on 2026-02-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the international trips scrolling section')),
                ('title', models.CharField(default='Explore International Trips', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'International Section Config',
                'verbose_name_plural': 'International Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country name for international trips', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in the international section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_international',
            field=models.BooleanField(default=False, help_text='Mark as international trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Short tagline for card overlay', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_international_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling international section'),
        ),
    ]
