# Generated by Django 6.0.1 on 2026-02-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_internationalsectionconfig_trip_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name if left blank', max_length=120, unique=True)),
                ('icon_image', models.URLField(blank=True, default='', help_text='URL to the circular category image')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower = shown first')),
                ('gradient_start', models.CharField(default='#3f9e8f', help_text='Hex color for ring gradient start', max_length=7)),
                ('gradient_end', models.CharField(default='#7ecfc0', help_text='Hex color for ring gradient end', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Assign trip to one or more categories', related_name='trips', to='core.category'),
        ),
    ]
