# Generated by Django 6.0.1 on 2026-02-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the India trips scrolling section')),
                ('title', models.CharField(default='Explore India Trips', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'India Section Config',
                'verbose_name_plural': 'India Section Config',
            },
        ),
        migrations.RemoveField(
            model_name='trip',
            name='categories',
        ),
        migrations.AddField(
            model_name='trip',
            name='india_display_order',
            field=models.IntegerField(default=0, help_text='Order in the India section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='india_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_india_trip',
            field=models.BooleanField(default=False, help_text='Mark as India trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_india_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling India section'),
        ),
        migrations.AddField(
            model_name='trip',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State/Region for India trips', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
