# Generated by Django 6.0.1 on 2026-02-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.URLField(blank=True, default='', help_text='Image URL for category card')),
                ('grad_start', models.CharField(default='#28a745', help_text='Gradient start color', max_length=20)),
                ('grad_end', models.CharField(default='#20c997', help_text='Gradient end color', max_length=20)),
                ('emoji', models.CharField(blank=True, default='🌅', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.category'),
        ),
    ]
