# Generated by Django 6.0.1 on 2026-02-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_category_trip_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='grad_end',
            field=models.CharField(blank=True, default='#2ecc71', help_text='Gradient end colour hex', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='grad_start',
            field=models.CharField(blank=True, default='#3f9e8f', help_text='Gradient start colour hex', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
