# Generated by Django 6.0.1 on 2026-02-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_category_options_remove_category_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneymoonSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the honeymoon trips scrolling section')),
                ('title', models.CharField(default='Honeymoon Getaways', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Honeymoon Section Config',
                'verbose_name_plural': 'Honeymoon Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='honeymoon_display_order',
            field=models.IntegerField(default=0, help_text='Order in the honeymoon section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_honeymoon',
            field=models.BooleanField(default=False, help_text='Mark as honeymoon trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_honeymoon_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling honeymoon section'),
        ),
    ]
