# Generated by Django 6.0.1 on 2026-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_honeymoonsectionconfig_trip_honeymoon_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HimalayanSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Himalayan treks scrolling section')),
                ('title', models.CharField(default='Majestic Himalayan Treks', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Himalayan Section Config',
                'verbose_name_plural': 'Himalayan Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='himalayan_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Himalayan section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_himalayan_trek',
            field=models.BooleanField(default=False, help_text='Mark as Himalayan trek'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_himalayan_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Himalayan section'),
        ),
    ]
