# Generated by Django 6.0.1 on 2026-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_himalayansectionconfig_trip_himalayan_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackpackingSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Backpacking trips scrolling section')),
                ('title', models.CharField(default='Adventure Backpacking', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Backpacking Section Config',
                'verbose_name_plural': 'Backpacking Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='backpacking_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Backpacking section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_backpacking_trip',
            field=models.BooleanField(default=False, help_text='Mark as Backpacking trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_backpacking_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Backpacking section'),
        ),
    ]
