# Generated by Django 6.0.1 on 2026-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_backpackingsectionconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Summer treks scrolling section')),
                ('title', models.CharField(default='Vibrant Summer Treks', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Summer Section Config',
                'verbose_name_plural': 'Summer Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='is_summer_trek',
            field=models.BooleanField(default=False, help_text='Mark as Summer trek'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_summer_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Summer section'),
        ),
        migrations.AddField(
            model_name='trip',
            name='summer_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Summer section (lower = first)'),
        ),
    ]
