# Generated by Django 6.0.1 on 2026-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_summersectionconfig_trip_is_summer_trek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsoonSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Monsoon treks scrolling section')),
                ('title', models.CharField(default='Misty Monsoon Treks', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Monsoon Section Config',
                'verbose_name_plural': 'Monsoon Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='is_monsoon_trek',
            field=models.BooleanField(default=False, help_text='Mark as Monsoon trek'),
        ),
        migrations.AddField(
            model_name='trip',
            name='monsoon_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Monsoon section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_monsoon_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Monsoon section'),
        ),
    ]
