# Generated by Django 6.0.1 on 2026-02-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_communitysectionconfig_trip_community_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Festival trips scrolling section')),
                ('title', models.CharField(default='Celebrate Festival Trips', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Festival Section Config',
                'verbose_name_plural': 'Festival Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='festival_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Festival section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_festival_trip',
            field=models.BooleanField(default=False, help_text='Mark as Festival trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_festival_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Festival section'),
        ),
    ]
