# Generated by Django 6.0.1 on 2026-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_festivalsectionconfig_trip_festival_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='featured_highlights',
            field=models.JSONField(blank=True, help_text='List of highlight labels for floating chips, e.g. ["Ubud · Rice Terraces", "Tanah Lot · Temples"]', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured trip (shows in Featured Destination section)'),
        ),
    ]
