# Generated by Django 6.0.1 on 2026-03-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_trip_featured_highlights_trip_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Adventure trips scrolling section')),
                ('title', models.CharField(default='Epic Adventure Trips', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Adventure Section Config',
                'verbose_name_plural': 'Adventure Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='adventure_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Adventure section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_adventure_trip',
            field=models.BooleanField(default=False, help_text='Mark as Adventure trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_adventure_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Adventure section'),
        ),
        migrations.CreateModel(
            name='TripGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(help_text='Cloudinary image URL')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('image_type', models.CharField(choices=[('GALLERY', 'Gallery'), ('MAP', 'Route Map'), ('REVIEW', 'Review Screenshot')], default='GALLERY', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Lower = displayed first')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.trip')),
            ],
            options={
                'verbose_name': 'Trip Gallery Image',
                'verbose_name_plural': 'Trip Gallery Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
