# Generated by Django 6.0.1 on 2026-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_adventuresectionconfig_trip_adventure_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration_nights',
            field=models.IntegerField(default=0),
        ),
    ]
