# Generated by Django 6.0.1 on 2026-03-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_trip_duration_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cancellation_policy',
            field=models.TextField(blank=True, default='', help_text='Cancellation policy text'),
        ),
        migrations.AddField(
            model_name='trip',
            name='drop_location',
            field=models.CharField(blank=True, default='', help_text='Drop city, e.g. Delhi', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='faqs',
            field=models.JSONField(blank=True, help_text='List of FAQ objects, e.g. [{"q": "...", "a": "..."}]', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='gallery_image_urls',
            field=models.JSONField(blank=True, help_text='List of Cloudinary image URLs for the photo gallery', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='overview',
            field=models.TextField(blank=True, default='', help_text='Rich overview / about text for the trip detail page'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(blank=True, default='', help_text='Pickup city, e.g. Delhi', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='things_to_pack',
            field=models.JSONField(blank=True, help_text='List of packing items, e.g. ["Warm jacket", "Trekking shoes"]', null=True),
        ),
    ]
