# Generated by Django 6.0.1 on 2026-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_trip_cancellation_policy_trip_drop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='batches',
            field=models.JSONField(blank=True, help_text='List of batch objects, e.g. [{"startDate": "...", "endDate": "...", "status": "Available/Filling Fast/Full"}]', null=True),
        ),
    ]
