# Generated by Django 6.0.1 on 2026-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_trip_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price_options',
            field=models.JSONField(blank=True, help_text='List of pricing options, e.g. [{"occupancy": "Triple", "price": 10000}, {"occupancy": "Double", "price": 12000}]', null=True),
        ),
    ]
