# Generated by Django 6.0.1 on 2026-03-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_trip_price_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='batch_details',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='itinerary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='occupancy_details',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
