# Generated by Django 6.0.1 on 2026-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_booking_batch_details_booking_itinerary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NorthIndiaSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the North India trips scrolling section')),
                ('title', models.CharField(default='Explore North India Trips', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'North India Section Config',
                'verbose_name_plural': 'North India Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='is_north_india_trip',
            field=models.BooleanField(default=False, help_text='Mark as North India trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='north_india_display_order',
            field=models.IntegerField(default=0, help_text='Order in the North India section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='north_india_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_north_india_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling North India section'),
        ),
    ]
