# Generated by Django 6.0.1 on 2026-03-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_northindiasectionconfig_trip_is_north_india_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HimachalSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Himachal trips scrolling section')),
                ('title', models.CharField(default='Explore Himachal Pradesh', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Himachal Section Config',
                'verbose_name_plural': 'Himachal Section Config',
            },
        ),
        migrations.CreateModel(
            name='UttarakhandSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Uttarakhand trips scrolling section')),
                ('title', models.CharField(default='Explore Uttarakhand', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Uttarakhand Section Config',
                'verbose_name_plural': 'Uttarakhand Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='himachal_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Himachal section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='himachal_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_himachal_trip',
            field=models.BooleanField(default=False, help_text='Mark as Himachal trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_uttarakhand_trip',
            field=models.BooleanField(default=False, help_text='Mark as Uttarakhand trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_himachal_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Himachal section'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_uttarakhand_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Uttarakhand section'),
        ),
        migrations.AddField(
            model_name='trip',
            name='uttarakhand_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Uttarakhand section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='uttarakhand_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
    ]
