# Generated by Django 6.0.1 on 2026-03-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_himachalsectionconfig_uttarakhandsectionconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='journey_in_frames_order',
            field=models.IntegerField(default=0, help_text='Order in the Journey in Frames section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_journey_in_frames',
            field=models.BooleanField(default=False, help_text='Show in the Journey in Frames gallery section'),
        ),
    ]
