# Generated by Django 6.0.1 on 2026-03-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_trip_journey_in_frames_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='good_friday_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Good Friday section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_good_friday_trip',
            field=models.BooleanField(default=False, help_text='Mark as Good Friday trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_good_friday_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Good Friday section'),
        ),
    ]
