# Generated by Django 6.0.1 on 2026-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_trip_good_friday_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code applied during booking', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied', max_digits=10),
        ),
    ]
