# Generated by Django 6.0.1 on 2026-03-23 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_booking_coupon_code_booking_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g. SUMMER20)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or Flat amount', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap for percentage coupons', max_digits=10, null=True)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum booking total required to apply coupon', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable/disable the coupon')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Coupon expiration date', null=True)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Max times coupon can be used overall (0 = unlimited)')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Counter for successful uses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, help_text='Restrict to specific trip (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.trip')),
                ('user', models.ForeignKey(blank=True, help_text='Restrict to specific user (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
