# Generated by Django 6.0.1 on 2026-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongWeekendSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Long Weekend trips scrolling section')),
                ('title', models.CharField(default='Long Weekend Gateways', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Long Weekend Section Config',
                'verbose_name_plural': 'Long Weekend Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='is_long_weekend_trip',
            field=models.BooleanField(default=False, help_text='Mark as Long Weekend trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='long_weekend_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Long Weekend section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='long_weekend_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_long_weekend_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Long Weekend section'),
        ),
    ]
