# Generated by Django 6.0.1 on 2026-03-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_longweekendsectionconfig_trip_is_long_weekend_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='honeymoon_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
    ]
