# Generated by Django 6.0.1 on 2026-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_trip_summer_featured_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='monsoon_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
    ]
