# Generated by Django 6.0.1 on 2026-03-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_trip_monsoon_featured_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='festival_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
    ]
