# Generated by Django 6.0.1 on 2026-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_trip_festival_featured_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikingSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the Biking trips scrolling section')),
                ('title', models.CharField(default='Epic Biking Trips', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Biking Section Config',
                'verbose_name_plural': 'Biking Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='biking_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Biking section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='biking_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_biking_trip',
            field=models.BooleanField(default=False, help_text='Mark as Biking trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_biking_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Biking section'),
        ),
    ]
