# Generated by Django 6.0.1 on 2026-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_bikingsectionconfig_trip_biking_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlsSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable the All Girls Group trips scrolling section')),
                ('title', models.CharField(default='All Girls Group Tours', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle below the heading', max_length=300)),
                ('scroll_speed', models.PositiveIntegerField(default=60, help_text='Animation duration in seconds (higher = slower)')),
            ],
            options={
                'verbose_name': 'Girls Section Config',
                'verbose_name_plural': 'Girls Section Config',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='girls_display_order',
            field=models.IntegerField(default=0, help_text='Order in the Girls Trips section (lower = first)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='girls_featured_priority',
            field=models.IntegerField(default=0, help_text='Featured priority (higher = more prominent)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_girls_trip',
            field=models.BooleanField(default=False, help_text='Mark as All Girls Group trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='show_in_girls_section',
            field=models.BooleanField(default=False, help_text='Show in the scrolling Girls Trips section'),
        ),
    ]
