from django.urls import path
from .views import (
    hello_api, trip_list, login_view, protected_test_view, signup_view,
    trip_detail, create_enquiry, my_enquiries, admin_enquiries, admin_trips,
    admin_trip_detail, admin_toggle_trip, admin_users, update_user_role,
    delete_user, contact_us, admin_contact_messages, delete_contact_message,
    create_booking, user_bookings, user_booking_detail, admin_bookings, update_booking_status,
    record_trip_view, recommended_trips,
    list_reviews, create_review,
    site_stats, admin_site_stats,
    international_trips, admin_international_config,
    india_trips, admin_india_config,
    north_india_trips, admin_north_india_config,
    honeymoon_trips, admin_honeymoon_config,
    himalayan_trips, admin_himalayan_config,
    backpacking_trips, admin_backpacking_config,
    summer_trips, admin_summer_config,
    monsoon_trips, admin_monsoon_config,
    community_trips, admin_community_config,
    festival_trips, admin_festival_config,
    adventure_trips, admin_adventure_config,
    himachal_trips, admin_himachal_config,
    uttarakhand_trips, admin_uttarakhand_config,
    featured_trips,
    request_password_reset, verify_reset_otp, reset_password,
    category_list, admin_categories,
    journey_in_frames_trips, trip_gallery_images, delete_trip_gallery_image,
    good_friday_trips, all_good_friday_trips,
    long_weekend_trips, admin_long_weekend_config,
    validate_coupon_view, admin_coupons, admin_coupon_detail,
    applicable_coupons_view,
)

urlpatterns = [
    path("v1/hello/", hello_api),
    path("v1/trips/", trip_list),
    path("v1/categories/", category_list),
    path("v1/admin/categories/", admin_categories),
    path("v1/trips/recommended/", recommended_trips),
    path("v1/trips/featured/", featured_trips),
    path("v1/trips/international/", international_trips),
    path("v1/trips/india/", india_trips),
    path("v1/trips/honeymoon/", honeymoon_trips),
    path("v1/admin/honeymoon-config/", admin_honeymoon_config),
    path("v1/trips/north-india/", north_india_trips),
    path("v1/admin/north-india-config/", admin_north_india_config),
    path("v1/trips/<int:pk>/", trip_detail),
    path("v1/trips/<int:pk>/view/", record_trip_view),
    path("v1/auth/login/", login_view),
    path("v1/auth/signup/", signup_view),
    path("v1/auth/protected/", protected_test_view),
    path("v1/auth/request-reset/", request_password_reset),
    path("v1/auth/verify-otp/", verify_reset_otp),
    path("v1/auth/reset-password/", reset_password),
    path("v1/enquiries/", create_enquiry),
    path("v1/my-enquiries/", my_enquiries),
    path("v1/admin/enquiries/", admin_enquiries),
    path("v1/admin/trips/", admin_trips),
    path("v1/admin/trips/<int:pk>/", admin_trip_detail),
    path("v1/admin/trips/<int:pk>/toggle/", admin_toggle_trip),
    path("v1/admin/users/", admin_users),
    path("v1/admin/users/<int:pk>/role/", update_user_role),
    path("v1/admin/users/<int:pk>/", delete_user),
    path("v1/contact/", contact_us),
    path("v1/admin/contact-messages/", admin_contact_messages),
    path("v1/admin/contact-messages/<int:pk>/", delete_contact_message),
    path("v1/bookings/create/", create_booking),
    path("v1/bookings/my/", user_bookings),
    path("v1/bookings/my/<int:pk>/", user_booking_detail),
    path("v1/admin/bookings/", admin_bookings),
    path("v1/admin/bookings/<int:pk>/status/", update_booking_status),
    path("v1/reviews/", list_reviews),
    path("v1/reviews/create/", create_review),
    path("v1/site-stats/", site_stats),
    path("v1/admin/site-stats/", admin_site_stats),
    path("v1/admin/site-stats/<int:pk>/", admin_site_stats),
    path("v1/admin/international-config/", admin_international_config),
    path("v1/admin/india-config/", admin_india_config),
    path("v1/trips/himalayan/", himalayan_trips),
    path("v1/admin/himalayan-config/", admin_himalayan_config),
    path("v1/trips/backpacking/", backpacking_trips),
    path("v1/admin/backpacking-config/", admin_backpacking_config),
    path("v1/trips/summer/", summer_trips),
    path("v1/admin/summer-config/", admin_summer_config),
    path("v1/trips/monsoon/", monsoon_trips),
    path("v1/admin/monsoon-config/", admin_monsoon_config),
    path("v1/trips/community/", community_trips),
    path("v1/admin/community-config/", admin_community_config),
    path("v1/trips/festival/", festival_trips),
    path("v1/admin/festival-config/", admin_festival_config),
    path("v1/trips/adventure/", adventure_trips),
    path("v1/admin/adventure-config/", admin_adventure_config),
    path("v1/trips/himachal/", himachal_trips),
    path("v1/admin/himachal-config/", admin_himachal_config),
    path("v1/trips/uttarakhand/", uttarakhand_trips),
    path("v1/admin/uttarakhand-config/", admin_uttarakhand_config),
    path("v1/gallery/journey-frames/", journey_in_frames_trips),
    path("v1/gallery/images/", trip_gallery_images),
    path("v1/gallery/images/<int:pk>/", delete_trip_gallery_image),
    path("v1/trips/good-friday/", good_friday_trips),
    path("v1/trips/good-friday/all/", all_good_friday_trips),
    path("v1/trips/long-weekend/", long_weekend_trips),
    path("v1/admin/long-weekend-config/", admin_long_weekend_config),
    
    # Coupons
    path("v1/coupons/validate/", validate_coupon_view),
    path("v1/coupons/applicable/", applicable_coupons_view),
    path("v1/admin/coupons/", admin_coupons),
    path("v1/admin/coupons/<int:pk>/", admin_coupon_detail),
]
